Add tests for Book and Category.
makaroshyna/online-book-store pull request #15
Opened 2024-05-27 20:52 UTC by makaroshyna

2024-06-03 09:02 UTC, karma-o requested changes
Looks very nice! left a few comments

2024-06-03 09:02 UTC, karma-o commented on src/test/java/makaroshyna/onlinebookstore/controller/BookControllerTest.java
> +    public void updateBookById_GivenValidData_ReturnsBook() throws Exception {
add cases with invalid id for update & delete

2024-06-03 09:02 UTC, karma-o commented on src/test/java/makaroshyna/onlinebookstore/controller/BookControllerTest.java
> +        expected.setCategoryIds(Set.of());
maybe we can have those type of variables like request DTOs initialized in the `before each`? to not duplicate the code in different methods, also variables like title, author, etc. could be constants

2024-06-03 09:02 UTC, karma-o commented on src/test/java/makaroshyna/onlinebookstore/controller/CategoryControllerTest.java
> +        towers.setPrice(BigDecimal.valueOf(490.95));
same here

2024-06-03 09:02 UTC, karma-o commented on src/test/java/makaroshyna/onlinebookstore/controller/CategoryControllerTest.java
> +    public void updateCategoryById_ValidId_ReturnsCategory() throws Exception {
same with id here, let's add cases where id that we have received does not exist

2024-06-03 09:02 UTC, karma-o commented on src/test/java/makaroshyna/onlinebookstore/service/BookServiceImplTest.java
> +        when(bookMapper.toDto(any())).thenReturn(bookDto);
I think it is better to keep things grouped by actions instead of entity type, please check other similar places as well
```suggestion
        CreateBookRequestDto requestDto = new CreateBookRequestDto();
        requestDto.setTitle("Test Title");

        Book book = new Book();
        book.setId(1L);
        book.setTitle("Test Title");

        BookDto bookDto = new BookDto();
        bookDto.setId(1L);
        bookDto.setTitle("Test Title");

        when(bookRepository.existsById(1L)).thenReturn(true);
        when(bookMapper.toModel(requestDto)).thenReturn(book);
        when(bookMapper.toDto(any())).thenReturn(bookDto);
```

2024-06-03 09:02 UTC, karma-o commented on src/test/java/makaroshyna/onlinebookstore/service/BookServiceImplTest.java
> +    }
we do not need a new service after each test, we also do not have to create it by hands, take a look at the `@InjectMocks`, same for other service test

2024-06-03 09:02 UTC, karma-o commented on src/test/java/makaroshyna/onlinebookstore/service/CategoryServiceImplTest.java
> +                "Test description");
duplicated information, can we extract it to some `before each`?

2024-06-04 21:17 UTC, makaroshyna commented on src/test/java/makaroshyna/onlinebookstore/service/BookServiceImplTest.java
> +    }
https://tedvinke.wordpress.com/2014/02/13/mockito-why-you-should-not-use-injectmocks-annotation-to-autowire-fields/
I had a problem with InjectMocks annotation already + I read some posts that it is better to instantiate this class directly. And how can you guarantee that all tests are independent without BeforeEach method?

2024-06-07 14:29 UTC, closed without merging