Add tests for Books and Categories.
makaroshyna/online-book-store pull request #17
Opened 2024-06-07 14:38 UTC by makaroshyna

2024-06-11 13:56 UTC, andrii-hoienko requested changes
Nice, left some minor comments

2024-06-11 13:56 UTC, andrii-hoienko commented on src/test/resources/database/categories/add-three-categories.sql
> +INSERT INTO categories (id, name, description) VALUES (3, 'Detective', 'Detective Description');
```suggestion
INSERT INTO categories (id, name, description) VALUES (3, 'Detective', 'Detective Description');

```

2024-06-11 13:56 UTC, andrii-hoienko commented on src/test/resources/database/teardown.sql
> +DELETE FROM categories;
```suggestion
DELETE FROM categories;

```

2024-06-11 13:56 UTC, andrii-hoienko commented on src/test/resources/database/categories/add-three-categories.sql
> +INSERT INTO categories (id, name, description) VALUES (3, 'Detective', 'Detective Description');
Check other files as well

2024-06-11 13:56 UTC, andrii-hoienko commented on src/test/java/makaroshyna/onlinebookstore/service/CategoryServiceImplTest.java
> +        verify(categoryRepository, times(1)).deleteById(1L);
times 1 is by default

2024-06-11 13:56 UTC, andrii-hoienko commented on src/test/java/makaroshyna/onlinebookstore/controller/BookControllerTest.java
> +
Code duplication

2024-06-11 14:07 UTC, makaroshyna commented
Pull request with previous comments:
https://github.com/makaroshyna/online-book-store/pull/15

2024-06-12 10:10 UTC, yevheniisynytsia requested changes
Well done! Some small comments left

2024-06-12 10:10 UTC, yevheniisynytsia commented on src/test/java/makaroshyna/onlinebookstore/service/BookServiceImplTest.java
> +@ExtendWith(MockitoExtension.class)
can be replaced by `@MockitoSettings` - a bit easier to remember =)

2024-06-12 10:10 UTC, yevheniisynytsia commented on src/test/java/makaroshyna/onlinebookstore/service/BookServiceImplTest.java
> +        bookService = new BookServiceImpl(bookRepository, bookMapper, bookSpecificationBuilder);
please use `@InjectMocks` instead

2024-06-12 10:10 UTC, yevheniisynytsia commented on src/test/java/makaroshyna/onlinebookstore/service/BookServiceImplTest.java
> +    private BookService bookService;
```suggestion
    @InjectMocks
    private BookService bookService;
```

2024-06-12 10:10 UTC, yevheniisynytsia commented on src/test/java/makaroshyna/onlinebookstore/service/BookServiceImplTest.java
> +    private BookDto responseDto;
I prefer such order: 
* constants
* objects (dtos and so on)
* mocks
* tested service

2024-06-12 10:10 UTC, yevheniisynytsia commented on src/test/java/makaroshyna/onlinebookstore/service/BookServiceImplTest.java
> +        assertEquals(result.size(), 1);
actually this is not a perfect assert. 
Let's imagine someone accidentally deleted one field from dto, but this field was required to be displayed on the UI.
Such assert won't catch such an error. 

Best practice would be to create expected objects and assertEquals expected with actual

2024-06-12 10:10 UTC, yevheniisynytsia commented on src/test/java/makaroshyna/onlinebookstore/service/BookServiceImplTest.java
> +        assertEquals(result.size(), 1);
this could be a thing to improve in future, so I think you may leave it as it is if you work on studying multithreading now

2024-06-24 13:36 UTC, makaroshyna commented on src/test/java/makaroshyna/onlinebookstore/service/BookServiceImplTest.java
> +        bookService = new BookServiceImpl(bookRepository, bookMapper, bookSpecificationBuilder);
I had a problem with InjectMocks annotation, and I read some posts that it is better to instantiate this class directly. You can read this article that tells that inject mocks is a bad practice: https://tedvinke.wordpress.com/2014/02/13/mockito-why-you-should-not-use-injectmocks-annotation-to-autowire-fields/

2024-06-25 09:29 UTC, karma-o approved these changes
Nice!

2025-03-07 20:51 UTC, merged