Add CustomGlobalExceptionHandler and data validation.
makaroshyna/online-book-store pull request #5
Opened 2024-04-29 15:50 UTC by makaroshyna

2024-04-29 20:56 UTC, JohnGrey17 approved these changes
GJ

2024-05-01 13:22 UTC, andrii-hoienko requested changes
Good job, but some improvements required

2024-05-01 13:22 UTC, andrii-hoienko commented on src/main/java/makaroshyna/onlinebookstore/dto/CreateBookRequestDto.java
>      private String isbn;
There is specific annotation to validate isbn

2024-05-01 13:22 UTC, andrii-hoienko commented on src/main/java/makaroshyna/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    }
Please add methods to handle exceptions that could occur in your code

2024-05-02 08:56 UTC, merged